# appveyor.yml

# Building, testing and deployment for Windows

# Syntax for this file:
# https://www.appveyor.com/docs/appveyor-yml
# see also https://www.appveyor.com/docs/windows-images-software/#python

image: Visual Studio 2019

build: false

environment:
  PY_DIR: C:/Python39

init: |
  - cmd: set "PATH=%PY_DIR%;%PY_DIR%\Scripts;%PATH%"
  - "python -V"

install:
  - "python -m pip install -r maintenance/requirements.txt"

test_script:
  - "python maintenance/github-crawler.py"
